# -*- coding: utf-8 -*
"""
usage:
    from common_constant import const
    print(const.ROOT_PATH)
"""
from constant import _Const

const = _Const()

const.CHANNEL_ID_CMD = 1
const.CHANNEL_ID_VIDEO = 2
const.CHANNEL_ID_MUSIC = 3
const.CHANNEL_ID_TTS = 4
const.CHANNEL_ID_VR = 5
const.CHANNEL_ID_TOUCH = 6

const.CHANNEL_CMD = 'Cmd'
const.CHANNEL_VIDEO = 'Video'
const.CHANNEL_MUSIC = 'Music'
const.CHANNEL_TTS = 'TTS'
const.CHANNEL_VR = 'VR'
const.CHANNEL_TOUCH = 'Touch'

const.PARSE_STATUS_PASS = 'Pass'
const.PARSE_STATUS_FAIL = 'Fail'

const.UNKNOWN = 'Unknown'
const.MAX_PRINT_MESSAGE_BYTES = 128

const.PACKET_HEADER_LENGTH = 8

const.PACKET_CMD_MESSAGE_HEADER_LENGTH = 8
const.PACKET_CMD_MESSAGE_HEADER_SERVICE_TYPE_OFFSET = 4
const.PACKET_CMD_MESSAGE_HEADER_SERVICE_TYPE_LENGTH = 4

const.PACKET_VIDEO_MESSAGE_HEADER_LENGTH = 12
const.PACKET_VIDEO_MESSAGE_HEADER_SERVICE_TYPE_OFFSET = 8
const.PACKET_VIDEO_MESSAGE_HEADER_SERVICE_TYPE_LENGTH = 4

const.PACKET_AUDIO_MESSAGE_HEADER_LENGTH = 12
const.PACKET_AUDIO_MESSAGE_HEADER_SERVICE_TYPE_OFFSET = 8
const.PACKET_AUDIO_MESSAGE_HEADER_SERVICE_TYPE_LENGTH = 4

const.PACKET_VR_MESSAGE_HEADER_LENGTH = 12
const.PACKET_VR_MESSAGE_HEADER_SERVICE_TYPE_OFFSET = 8
const.PACKET_VR_MESSAGE_HEADER_SERVICE_TYPE_LENGTH = 4

const.PACKET_TOUCH_MESSAGE_HEADER_LENGTH = 8
const.PACKET_TOUCH_MESSAGE_HEADER_SERVICE_TYPE_OFFSET = 4
const.PACKET_TOUCH_MESSAGE_HEADER_SERVICE_TYPE_LENGTH = 4

const.MAX_RAW_DATA_ASCII_PER_LINE = 24
const.MAX_RAW_DATA_BYTES_PER_LINE = 3 * const.MAX_RAW_DATA_ASCII_PER_LINE

const.ACCESSORY_HU = 'HU'
const.ACCESSORY_MD = 'MD'

const.MODULE_STATUS_UNKNOWN = 'unknown'

const.MODULE_PHONE_NAME = 'Phone'
const.MODULE_PHONE_STATUS_IDLE = 'idle'
const.MODULE_PHONE_STATUS_INCOMING = 'incoming'
const.MODULE_PHONE_STATUS_OUTING = 'outing'
const.MODULE_PHONE_STATUS_CONNECTED = 'connected'

const.MODULE_NAVI_NAME = 'Navi'
const.MODULE_NAVI_STATUS_IDLE = 'idle'
const.MODULE_NAVI_STATUS_START = 'start'

const.MODULE_MUSIC_NAME = 'Music'
const.MODULE_MUSIC_STATUS_IDLE = 'idle'
const.MODULE_MUSIC_STATUS_RUNNING = 'running'

const.MODULE_VR_NAME = 'VR'
const.MODULE_VR_STATUS_RECORD_IDLE = 'idle'
const.MODULE_VR_STATUS_RECORD_RUNNING = 'running'

const.MODULE_CONNECT_NAME = 'Connect'
const.MODULE_CONNECT_STATUS_ADB = 'adb'
const.MODULE_CONNECT_STATUS_AOA = 'aoa'
const.MODULE_CONNECT_STATUS_NCM_ANDROID = 'ncm android'
const.MODULE_CONNECT_STATUS_IOS = 'ios'
const.MODULE_CONNECT_STATUS_WIFI = 'wifi'

const.MODULE_MIC_NAME = 'Mic'
const.MODULE_MIC_STATUS_USE_VEHICLE_MIC = 'vehicle'
const.MODULE_MIC_STATUS_USE_MOBILE_MIC = 'mobile'

const.MODULE_MEDIAPCM_NAME = 'MediaPCM'
const.MODULE_MEDIAPCM_STATUS_IDLE = 'idle'
const.MODULE_MEDIAPCM_STATUS_RUNNING = 'running'

const.MODULE_EDOG_NAME = 'EDog'
const.MODULE_EDOG_STATUS_IDLE = 'idle'
const.MODULE_EDOG_STATUS_RUNNING = 'running'

const.MODULE_CRUISE_NAME = 'Cruise'
const.MODULE_CRUISE_STATUS_IDLE = 'idle'
const.MODULE_CRUISE_STATUS_RUNNING = 'running'

const.CAR_DATA_GPS_NAME = 'GPS'
const.CAR_DATA_VELOCITY_NAME = 'VELOCITY'
const.CAR_DATA_GYROSCOPE_NAME = 'GYROSCOPE'
const.CAR_DATA_ACCELERATION_NAME = 'ACCELERATION'
const.CAR_DATA_GEAR_NAME = 'GEAR'
const.CAR_DATA_OIL_NAME = 'OIL'

const.COORDINATE_SYSTEM_WGS84_ID = 1
const.COORDINATE_SYSTEM_WGS84_NAME = 'WGS-84'

const.COORDINATE_SYSTEM_GCJ02_ID = 2
const.COORDINATE_SYSTEM_GCJ02_NAME = 'GCJ-02'

const.PLAYMODE_REPEAT_ONE_NAME = 'repeat one'
const.PLAYMODE_SHUFFLE_NAME = 'shuffle'
const.PLAYMODE_REPEAT_ALL_NAME = 'repeat all'

const.TYPE_ENCORDER_ERROR_ID = 1
const.TYPE_ENCORDER_ERROR_NAME = 'encorder error'

const.TYPE_PERMISSION_DENIED_ID = 2
const.TYPE_PERMISSION_DENIED_NAME = 'permission denied'

const.TYPE_SCREENSHARE_REQUEST_ID = 3
const.TYPE_SCREENSHARE_REQUEST_NAME = 'screenshare request'

const.ACTION_DOWN_ID = 0
const.ACTION_DOWN_NAME = 'down'

const.ACTION_UP_ID = 1
const.ACTION_UP_NAME = 'up'

const.ACTION_MOVE_ID = 2
const.ACTION_MOVE_NAME = 'move'

const.KEYCODE_HOME_ID = 0x00000001
const.KEYCODE_HOME_NAME = 'home'

const.KEYCODE_PHONE_CALL_ID = 0x00000002
const.KEYCODE_PHONE_CALL_NAME = 'phone call'

const.KEYCODE_PHONE_END_ID = 0x00000003
const.KEYCODE_PHONE_END_NAME = 'phone end'

const.KEYCODE_PHONE_END_MUTE_ID = 0x00000004
const.KEYCODE_PHONE_END_MUTE_NAME = 'phone end mute(deprecated)'

const.KEYCODE_HFP_ID = 0x00000005
const.KEYCODE_HFP_NAME = 'hfp'

const.KEYCODE_SELECTOR_NEXT_ID = 0x00000006
const.KEYCODE_SELECTOR_NEXT_NAME = 'selector next'

const.KEYCODE_SELECTOR_PREVIOUS_ID = 0x00000007
const.KEYCODE_SELECTOR_PREVIOUS_NAME = 'selector previous'

const.KEYCODE_SETTING_ID = 0x00000008
const.KEYCODE_SETTING_NAME = 'setting(deprecated)'

const.KEYCODE_MEDIA_ID = 0x00000009
const.KEYCODE_MEDIA_NAME = 'media'

const.KEY_CODE_RADIO_ID = 0x0000000A
const.KEY_CODE_RADIO_NAME = 'radio(deprecated)'

const.KEYCODE_NAVI_ID = 0x0000000B
const.KEYCODE_NAVI_NAME = 'navi'

const.KEYCODE_SRC_ID = 0x0000000C
const.KEYCODE_SRC_NAME = 'src(deprecated)'

const.KEYCODE_MODE_ID = 0x0000000D
const.KEYCODE_MODE_NAME = 'mode(deprecated)'

const.KEYCODE_BACK_ID = 0x0000000E
const.KEYCODE_BACK_NAME = 'back'

const.KEYCODE_SEEK_SUB_ID = 0x0000000F
const.KEYCODE_SEEK_SUB_NAME = 'seek sub'

const.KEYCODE_SEEK_ADD_ID = 0x00000010
const.KEYCODE_SEEK_ADD_NAME = 'seek add'

const.KEYCODE_VOLUME_SUB_ID = 0x00000011
const.KEYCODE_VOLUME_SUB_NAME = 'volume sub(deprecated)'

const.KEYCODE_VOLUME_ADD_ID = 0x00000012
const.KEYCODE_VOLUME_ADD_NAME = 'volume add(deprecated)'

const.KEYCODE_MUTE_ID = 0x00000013
const.KEYCODE_MUTE_NAME = 'mute'

const.KEYCODE_OK_ID = 0x00000014
const.KEYCODE_OK_NAME = 'ok'

const.KEYCODE_MOVE_LEFT_ID = 0x00000015
const.KEYCODE_MOVE_LEFT_NAME = 'move left'

const.KEYCODE_MOVE_RIGHT_ID = 0x00000016
const.KEYCODE_MOVE_RIGHT_NAME = 'move right'

const.KEYCODE_MOVE_UP_ID = 0x00000017
const.KEYCODE_MOVE_UP_NAME = 'move up'

const.KEYCODE_MOVE_DOWN_ID = 0x00000018
const.KEYCODE_MOVE_DOWN_NAME = 'move down'

const.KEYCODE_MOVE_UP_LEFT_ID = 0x00000019
const.KEYCODE_MOVE_UP_LEFT_NAME = 'move up left'

const.KEYCODE_MOVE_UP_RIGHT_ID = 0x0000001A
const.KEYCODE_MOVE_UP_RIGHT_NAME = 'move up right'

const.KEYCODE_MOVE_DOWN_LEFT_ID = 0x0000001B
const.KEYCODE_MOVE_DOWN_LEFT_NAME = 'move down left'

const.KEYCODE_MOVE_DOWN_RIGHT_ID = 0x0000001C
const.KEYCODE_MOVE_DOWN_RIGHT_NAME = 'move down right'

const.KEYCODE_TEL_ID = 0x0000001D
const.KEYCODE_TEL_NAME = 'telephone'

const.KEYCODE_MAIN_ID = 0x0000001E
const.KEYCODE_MAIN_NAME = 'main'

const.KEYCODE_MEDIA_START_ID = 0x0000001F
const.KEYCODE_MEDIA_START_NAME = 'media start'

const.KEYCODE_MEDIA_STOP_ID = 0x00000020
const.KEYCODE_MEDIA_STOP_NAME = 'media stop'

const.KEYCODE_VR_START_ID = 0x00000021
const.KEYCODE_VR_START_NAME = 'vr start'

const.KEYCODE_VR_STOP_ID = 0x00000022
const.KEYCODE_VR_STOP_NAME = 'vr stop'

const.KEYCODE_NUMBER_0_ID = 0x00000023
const.KEYCODE_NUMBER_0_NAME = '0'

const.KEYCODE_NUMBER_1_ID = 0x00000024
const.KEYCODE_NUMBER_1_NAME = '1'

const.KEYCODE_NUMBER_2_ID = 0x00000025
const.KEYCODE_NUMBER_2_NAME = '2'

const.KEYCODE_NUMBER_3_ID = 0x00000026
const.KEYCODE_NUMBER_3_NAME = '3'

const.KEYCODE_NUMBER_4_ID = 0x00000027
const.KEYCODE_NUMBER_4_NAME = '4'

const.KEYCODE_NUMBER_5_ID = 0x00000028
const.KEYCODE_NUMBER_5_NAME = '5'

const.KEYCODE_NUMBER_6_ID = 0x00000029
const.KEYCODE_NUMBER_6_NAME = '6'

const.KEYCODE_NUMBER_7_ID = 0x0000002A
const.KEYCODE_NUMBER_7_NAME = '7'

const.KEYCODE_NUMBER_8_ID = 0x0000002B
const.KEYCODE_NUMBER_8_NAME = '8'

const.KEYCODE_NUMBER_9_ID = 0x0000002C
const.KEYCODE_NUMBER_9_NAME = '9'

const.KEYCODE_NUMBER_10_ID = 0x0000002D
const.KEYCODE_NUMBER_10_NAME = '*'

const.KEYCODE_NUMBER_11_ID = 0x0000002E
const.KEYCODE_NUMBER_11_NAME = '#'

const.KEYCODE_NUMBER_DEL_ID = 0x0000002F
const.KEYCODE_NUMBER_DEL_NAME = 'delete'

const.KEYCODE_NUMBER_CLEAR_ID = 0x00000030
const.KEYCODE_NUMBER_CLEAR_NAME = 'clear'

const.KEYCODE_NUMBER_PLUS_ID = 0x00000031
const.KEYCODE_NUMBER_PLUS_NAME = '+'



### Cmd ###
const.MSG_CMD_HU_PROTOCOL_VERSION_SERVICE_TYPE = '0x00018001'
const.MSG_CMD_HU_PROTOCOL_VERSION_SERVICE_NAME = 'MSG_CMD_HU_PROTOCOL_VERSION'

const.MSG_CMD_PROTOCOL_VERSION_MATCH_STATUS_SERVICE_TYPE = '0x00010002'
const.MSG_CMD_PROTOCOL_VERSION_MATCH_STATUS_SERVICE_NAME = 'MSG_CMD_PROTOCOL_VERSION_MATCH_STATUS'

const.MSG_CMD_HU_INFO_SERVICE_TYPE = '0x00018003'
const.MSG_CMD_HU_INFO_SERVICE_NAME = 'MSG_CMD_HU_INFO'

const.MSG_CMD_MD_INFO_SERVICE_TYPE = '0x00010004'
const.MSG_CMD_MD_INFO_SERVICE_NAME = 'MSG_CMD_MD_INFO'

const.MSG_CMD_HU_BT_OOB_INFO_SERVICE_TYPE = '0x00018005'
const.MSG_CMD_HU_BT_OOB_INFO_SERVICE_NAME = 'MSG_CMD_HU_BT_OOB_INFO'

const.MSG_CMD_MD_BT_OOB_INFO_SERVICE_TYPE = '0x00010006'
const.MSG_CMD_MD_BT_OOB_INFO_SERVICE_NAME = 'MSG_CMD_MD_BT_OOB_INFO'

const.MSG_CMD_VIDEO_ENCODER_INIT_SERVICE_TYPE = '0x00018007'
const.MSG_CMD_VIDEO_ENCODER_INIT_SERVICE_NAME = 'MSG_CMD_VIDEO_ENCODER_INIT'

const.MSG_CMD_VIDEO_ENCODER_INIT_DONE_SERVICE_TYPE = '0x00010008'
const.MSG_CMD_VIDEO_ENCODER_INIT_DONE_SERVICE_NAME = 'MSG_CMD_VIDEO_ENCODER_INIT_DONE'

const.MSG_CMD_VIDEO_ENCODER_START_SERVICE_TYPE = '0x00018009'
const.MSG_CMD_VIDEO_ENCODER_START_SERVICE_NAME = 'MSG_CMD_VIDEO_ENCODER_START'

const.MSG_CMD_VIDEO_ENCODER_PAUSE_SERVICE_TYPE = '0x0001800A'
const.MSG_CMD_VIDEO_ENCODER_PAUSE_SERVICE_NAME = 'MSG_CMD_VIDEO_ENCODER_PAUSE'

const.MSG_CMD_VIDEO_ENCODER_RESET_SERVICE_TYPE = '0x0001800B'
const.MSG_CMD_VIDEO_ENCODER_RESET_SERVICE_NAME = 'MSG_CMD_VIDEO_ENCODER_RESET'

const.MSG_CMD_VIDEO_ENCODER_FRAME_RATE_CHANGE_SERVICE_TYPE = '0x0001800C'
const.MSG_CMD_VIDEO_ENCODER_FRAME_RATE_CHANGE_SERVICE_NAME = 'MSG_CMD_VIDEO_ENCODER_FRAME_RATE_CHANGE'

const.MSG_CMD_VIDEO_ENCODER_FRAME_RATE_CHANGE_DONE_SERVICE_TYPE = '0x0001000D'
const.MSG_CMD_VIDEO_ENCODER_FRAME_RATE_CHANGE_DONE_SERVICE_NAME = 'MSG_CMD_VIDEO_ENCODER_FRAME_RATE_CHANGE_DONE'

const.MSG_CMD_CAR_VELOCITY_SERVICE_TYPE = '0x0001800F'
const.MSG_CMD_CAR_VELOCITY_SERVICE_NAME = 'MSG_CMD_CAR_VELOCITY'

const.MSG_CMD_CAR_GPS_SERVICE_TYPE = '0x00018010'
const.MSG_CMD_CAR_GPS_SERVICE_NAME = 'MSG_CMD_CAR_GPS_SERVICE_NAME'

const.MSG_CMD_CAR_GYROSCOPE_SERVICE_TYPE = '0x00018011'
const.MSG_CMD_CAR_GYROSCOPE_SERVICE_NAME = 'MSG_CMD_CAR_GYROSCOPE'

const.MSG_CMD_CAR_ACCELERATION_SERVICE_TYPE = '0x00018012'
const.MSG_CMD_CAR_ACCELERATION_SERVICE_NAME = 'MSG_CMD_CAR_ACCELERATION'

const.MSG_CMD_CAR_OIL_SERVICE_TYPE = '0x00018013'
const.MSG_CMD_CAR_OIL_SERVICE_NAME = 'MSG_CMD_CAR_OIL'

const.MSG_CMD_SCREEN_ON_SERVICE_TYPE = '0x00010018'
const.MSG_CMD_SCREEN_ON_SERVICE_NAME = 'MSG_CMD_SCREEN_ON'

const.MSG_CMD_SCREEN_OFF_SERVICE_TYPE = '0x00010019'
const.MSG_CMD_SCREEN_OFF_SERVICE_NAME = 'MSG_CMD_SCREEN_OFF'

const.MSG_CMD_SCREEN_USERPRESENT_SERVICE_TYPE = '0x0001001A'
const.MSG_CMD_SCREEN_USERPRESENT_SERVICE_NAME = 'MSG_CMD_SCREEN_USERPRESENT'

const.MSG_CMD_FOREGROUND_SERVICE_TYPE = '0x0001001B'
const.MSG_CMD_FOREGROUND_SERVICE_NAME = 'MSG_CMD_FOREGROUND'

const.MSG_CMD_BACKGROUND_SERVICE_TYPE = '0x0001001C'
const.MSG_CMD_BACKGROUND_SERVICE_NAME = 'MSG_CMD_BACKGROUND'

const.MSG_CMD_LAUNCH_MODE_NORMAL_SERVICE_TYPE = '0x0001801D'
const.MSG_CMD_LAUNCH_MODE_NORMAL_SERVICE_NAME = 'MSG_CMD_LAUNCH_MODE_NORMAL'

const.MSG_CMD_LAUNCH_MODE_PHONE_SERVICE_TYPE = '0x0001801E'
const.MSG_CMD_LAUNCH_MODE_PHONE_SERVICE_NAME = 'MSG_CMD_LAUNCH_MODE_PHONE'

const.MSG_CMD_LAUNCH_MODE_MAP_SERVICE_TYPE = '0x0001801F'
const.MSG_CMD_LAUNCH_MODE_MAP_SERVICE_NAME = 'MSG_CMD_LAUNCH_MODE_MAP'

const.MSG_CMD_LAUNCH_MODE_MUSIC_SERVICE_TYPE = '0x00018020'
const.MSG_CMD_LAUNCH_MODE_MUSIC_SERVICE_NAME = 'MSG_CMD_LAUNCH_MODE_MUSIC'

const.MSG_CMD_GO_TO_DESKTOP_SERVICE_TYPE = '0x00010021'
const.MSG_CMD_GO_TO_DESKTOP_SERVICE_NAME = 'MSG_CMD_GO_TO_DESKTOP'

const.MSG_CMD_MIC_RECORD_WAKEUP_START_SERVICE_TYPE = '0x00010022'
const.MSG_CMD_MIC_RECORD_WAKEUP_START_SERVICE_NAME = 'MSG_CMD_MIC_RECORD_WAKEUP_START'

const.MSG_CMD_MIC_RECORD_END_SERVICE_TYPE = '0x00010023'
const.MSG_CMD_MIC_RECORD_END_SERVICE_NAME = 'MSG_CMD_MIC_RECORD_END'

const.MSG_CMD_MIC_RECORD_RECOG_START_SERVICE_TYPE = '0x00010024'
const.MSG_CMD_MIC_RECORD_RECOG_START_SERVICE_NAME = 'MSG_CMD_MIC_RECORD_RECOG_START'

const.MSG_CMD_GO_TO_FOREGROUND_SERVICE_TYPE = '0x00018025'
const.MSG_CMD_GO_TO_FOREGROUND_SERVICE_NAME = 'MSG_CMD_GO_TO_FOREGROUND'

const.MSG_CMD_MODULE_STATUS_SERVICE_TYPE = '0x00010026'
const.MSG_CMD_MODULE_STATUS_SERVICE_NAME = 'MSG_CMD_MODULE_STATUS'

const.MSG_CMD_STATISTIC_INFO_SERVICE_TYPE = '0x00018027'
const.MSG_CMD_STATISTIC_INFO_SERVICE_NAME = 'MSG_CMD_STATISTIC_INFO'

const.MSG_CMD_MODULE_CONTROL_SERVICE_TYPE = '0x00018028'
const.MSG_CMD_MODULE_CONTROL_SERVICE_NAME = 'MSG_CMD_MODULE_CONTROL'

const.MSG_CMD_CAR_DATA_GEAR_SERVICE_TYPE = '0x00018029'
const.MSG_CMD_CAR_DATA_GEAR_SERVICE_NAME = 'MSG_CMD_CAR_DATA_GEAR'

const.MSG_CMD_NAVI_NEXT_TURN_INFO_SERVICE_TYPE = '0x00010030'
const.MSG_CMD_NAVI_NEXT_TURN_INFO_SERVICE_NAME = 'MSG_CMD_NAVI_NEXT_TURN_INFO'

const.MSG_CMD_CAR_DATA_SUBSCRIBE_SERVICE_TYPE = '0x00010031'
const.MSG_CMD_CAR_DATA_SUBSCRIBE_SERVICE_NAME = 'MSG_CMD_CAR_DATA_SUBSCRIBE'

const.MSG_CMD_CAR_DATA_SUBSCRIBE_DONE_SERVICE_TYPE = '0x00018032'
const.MSG_CMD_CAR_DATA_SUBSCRIBE_DONE_SERVICE_NAME = 'MSG_CMD_CAR_DATA_SUBSCRIBE_DONE'

const.MSG_CMD_CAR_DATA_SUBSCRIBE_START_SERVICE_TYPE = '0x00010033'
const.MSG_CMD_CAR_DATA_SUBSCRIBE_START_SERVICE_NAME = 'MSG_CMD_CAR_DATA_SUBSCRIBE_START'

const.MSG_CMD_CAR_DATA_SUBSCRIBE_STOP_SERVICE_TYPE = '0x00010034'
const.MSG_CMD_CAR_DATA_SUBSCRIBE_STOP_SERVICE_NAME = 'MSG_CMD_CAR_DATA_SUBSCRIBE_STOP'

const.MSG_CMD_MEDIA_INFO_SERVICE_TYPE = '0x00010035'
const.MSG_CMD_MEDIA_INFO_SERVICE_NAME = 'MSG_CMD_MEDIA_INFO'

const.MSG_CMD_MEDIA_PROGRESS_BAR_SERVICE_TYPE = '0x00010036'
const.MSG_CMD_MEDIA_PROGRESS_BAR_SERVICE_NAME = 'MSG_CMD_MEDIA_PROGRESS_BAR'

const.MSG_CMD_CONNECT_EXCEPTION_SERVICE_TYPE = '0x00010037'
const.MSG_CMD_CONNECT_EXCEPTION_SERVICE_NAME = 'MSG_CMD_CONNECT_EXCEPTION'

const.MSG_CMD_REQUEST_GO_TO_FOREGROUND_SERVICE_TYPE = '0x00010038'
const.MSG_CMD_REQUEST_GO_TO_FOREGROUND_SERVICE_NAME = 'MSG_CMD_REQUEST_GO_TO_FOREGROUND'

const.MSG_CMD_UI_ACTION_SOUND_SERVICE_TYPE = '0x00010039'
const.MSG_CMD_UI_ACTION_SOUND_SERVICE_NAME = 'MSG_CMD_UI_ACTION_SOUND'

const.MSG_CMD_BT_HFP_REQUEST_SERVICE_TYPE = '0x00010040'
const.MSG_CMD_BT_HFP_REQUEST_SERVICE_NAME = 'MSG_CMD_BT_HFP_REQUEST'

const.MSG_CMD_BT_HFP_INDICATION_SERVICE_TYPE = '0x00018041'
const.MSG_CMD_BT_HFP_INDICATION_SERVICE_NAME = 'MSG_CMD_BT_HFP_INDICATION'

const.MSG_CMD_BT_HFP_CONNECTION_SERVICE_TYPE = '0x00018042'
const.MSG_CMD_BT_HFP_CONNECTION_SERVICE_NAME = 'MSG_CMD_BT_HFP_CONNECTION'

const.MSG_CMD_CARLIFE_DATA_SUBSCRIBE_SERVICE_TYPE = '0x00018043'
const.MSG_CMD_CARLIFE_DATA_SUBSCRIBE_SERVICE_NAME = 'MSG_CMD_CARLIFE_DATA_SUBSCRIBE'

const.MSG_CMD_CARLIFE_DATA_SUBSCRIBE_DONE_SERVICE_TYPE = '0x00010044'
const.MSG_CMD_CARLIFE_DATA_SUBSCRIBE_DONE_SERVICE_NAME = 'MSG_CMD_CARLIFE_DATA_SUBSCRIBE_DONE'

const.MSG_CMD_CARLIFE_DATA_SUBSCRIBE_START_SERVICE_TYPE = '0x00018045'
const.MSG_CMD_CARLIFE_DATA_SUBSCRIBE_START_SERVICE_NAME = 'MSG_CMD_CARLIFE_DATA_SUBSCRIBE_START'

const.MSG_CMD_CARLIFE_DATA_SUBSCRIBE_STOP_SERVICE_TYPE = '0x00018046'
const.MSG_CMD_CARLIFE_DATA_SUBSCRIBE_STOP_SERVICE_NAME = 'MSG_CMD_CARLIFE_DATA_SUBSCRIBE_STOP'

const.MSG_CMD_NAVI_ASSITANTGUIDE_INFO_SERVICE_TYPE = '0x00010047'
const.MSG_CMD_NAVI_ASSITANTGUIDE_INFO_SERVICE_NAME = 'MSG_CMD_NAVI_ASSITANTGUIDE_INFO'

const.MSG_CMD_HU_AUTHEN_REQUEST_SERVICE_TYPE = '0x00018048'
const.MSG_CMD_HU_AUTHEN_REQUEST_SERVICE_NAME = 'MSG_CMD_HU_AUTHEN_REQUEST'

const.MSG_CMD_MD_AUTHEN_RESPONSE_SERVICE_TYPE = '0x00010049'
const.MSG_CMD_MD_AUTHEN_RESPONSE_SERVICE_NAME = 'MSG_CMD_MD_AUTHEN_RESPONSE'

const.MSG_CMD_HU_AUTHEN_RESULT_SERVICE_TYPE = '0x0001804A'
const.MSG_CMD_HU_AUTHEN_RESULT_SERVICE_NAME = 'MSG_CMD_HU_AUTHEN_RESULT'

const.MSG_CMD_MD_AUTHEN_RESULT_SERVICE_TYPE = '0x0001004B'
const.MSG_CMD_MD_AUTHEN_RESULT_SERVICE_NAME = 'MSG_CMD_MD_AUTHEN_RESULT'

const.MSG_CMD_GO_TO_FOREGROUND_RESPONSE_SERVICE_TYPE = '0x0001004C'
const.MSG_CMD_GO_TO_FOREGROUND_RESPONSE_SERVICE_NAME = 'MSG_CMD_GO_TO_FOREGROUND_RESPONSE'

const.MSG_CMD_START_BT_AUTOPAIR_REQUEST_SERVICE_TYPE = '0x0001004D'
const.MSG_CMD_START_BT_AUTOPAIR_REQUEST_SERVICE_NAME = 'MSG_CMD_START_BT_AUTOPAIR_REQUEST'

const.MSG_CMD_BT_HFP_RESPONSE_SERVICE_TYPE = '0x0001804E'
const.MSG_CMD_BT_HFP_RESPONSE_SERVICE_NAME = 'MSG_CMD_BT_HFP_RESPONSE'

const.MSG_CMD_BT_HFP_STATUS_REQUEST_SERVICE_TYPE = '0x0001004F'
const.MSG_CMD_BT_HFP_STATUS_REQUEST_SERVICE_NAME = 'MSG_CMD_BT_HFP_STATUS_REQUEST'

const.MSG_CMD_BT_HFP_STATUS_RESPONSE_SERVICE_TYPE = '0x00018050'
const.MSG_CMD_BT_HFP_STATUS_RESPONSE_SERVICE_NAME = 'MSG_CMD_BT_HFP_STATUS_RESPONSE'

const.MSG_CMD_MD_FEATURE_CONFIG_REQUEST_SERVICE_TYPE = '0x00010051'
const.MSG_CMD_MD_FEATURE_CONFIG_REQUEST_SERVICE_NAME = 'MSG_CMD_MD_FEATURE_CONFIG_REQUEST'

const.MSG_CMD_HU_FEATURE_CONFIG_RESPONSE_SERVICE_TYPE = '0x00018052'
const.MSG_CMD_HU_FEATURE_CONFIG_RESPONSE_SERVICE_NAME = 'MSG_CMD_HU_FEATURE_CONFIG_RESPONSE'

const.MSG_CMD_BT_START_IDENTIFY_REQ_SERVICE_TYPE = '0x00018053'
const.MSG_CMD_BT_START_IDENTIFY_REQ_SERVICE_NAME = 'MSG_CMD_BT_START_IDENTIFY_REQ'

const.MSG_CMD_BT_IDENTIFY_RESULT_IND_SERVICE_TYPE = '0x00010054'
const.MSG_CMD_BT_IDENTIFY_RESULT_IND_SERVICE_NAME = 'MSG_CMD_BT_IDENTIFY_RESULT_IND'

const.MSG_CMD_ERROR_CODE_SERVICE_TYPE = '0x00018055'
const.MSG_CMD_ERROR_CODE_SERVICE_NAME = 'MSG_CMD_ERROR_CODE'

const.MSG_CMD_VIDEO_ENCODER_JPEG_SERVICE_TYPE = '0x00018056'
const.MSG_CMD_VIDEO_ENCODER_JPEG_SERVICE_NAME = 'MSG_CMD_VIDEO_ENCODER_JPEG'


const.MSG_CMD_VIDEO_ENCODER_JPEG_ACK_SERVICE_TYPE = '0x00010057'
const.MSG_CMD_VIDEO_ENCODER_JPEG_ACK_SERVICE_NAME = 'MSG_CMD_VIDEO_ENCODER_JPEG_ACK'

const.MSG_CMD_BT_HFP_CALL_STATUS_COVER_SERVICE_TYPE = '0x00010058'
const.MSG_CMD_BT_HFP_CALL_STATUS_COVER_SERVICE_NAME = 'MSG_CMD_BT_HFP_CALL_STATUS_COVER'

const.MSG_CMD_MD_EXIT_SERVICE_TYPE = '0x00010059'
const.MSG_CMD_MD_EXIT_SERVICE_NAME = 'MSG_CMD_MD_EXIT'

const.MSG_CMD_HU_CONNECT_STATISTIC_SERVICE_TYPE = '0x00018070'
const.MSG_CMD_HU_CONNECT_STATISTIC_SERVICE_NAME = 'MSG_CMD_HU_CONNECT_STATISTIC'

### Video ###
const.MSG_VIDEO_DATA_SERVICE_TYPE = '0x00020001'
const.MSG_VIDEO_DATA_SERVICE_NAME = 'MSG_VIDEO_DATA'

const.MSG_VIDEO_HEARTBEAT_SERVICE_TYPE = '0x00020002'
const.MSG_VIDEO_HEARTBEAT_SERVICE_NAME = 'MSG_VIDEO_HEARTBEAT'


### Music ###
const.MSG_MEDIA_INIT_SERVICE_TYPE = '0x00030001'
const.MSG_MEDIA_INIT_SERVICE_NAME = 'MSG_MEDIA_INIT'

const.MSG_MEDIA_PAUSE_SERVICE_TYPE = '0x00030003'
const.MSG_MEDIA_PAUSE_SERVICE_NAME = 'MSG_MEDIA_PAUSE'

const.MSG_MEDIA_RESUME_PLAY_SERVICE_TYPE = '0x00030004'
const.MSG_MEDIA_RESUME_PLAY_SERVICE_NAME = 'MSG_MEDIA_RESUME_PLAY'

const.MSG_MEDIA_DATA_SERVICE_TYPE = '0x00030006'
const.MSG_MEDIA_DATA_SERVICE_NAME = 'MSG_MEDIA_DATA'

### TTS ###
const.MSG_NAVI_TTS_INIT_SERVICE_TYPE = '0x00040001'
const.MSG_NAVI_TTS_INIT_SERVICE_NAME = 'MSG_NAVI_TTS_INIT'

const.MSG_NAVI_TTS_END_SERVICE_TYPE = '0x00040002'
const.MSG_NAVI_TTS_END_SERVICE_NAME = 'MSG_NAVI_TTS_END'

const.MSG_NAVI_TTS_DATA_SERVICE_TYPE = '0x00040003'
const.MSG_NAVI_TTS_DATA_SERVICE_NAME = 'MSG_NAVI_TTS_DATA'

### VR ###
const.MSG_VR_DATA_SERVICE_TYPE = '0x00058001'
const.MSG_VR_DATA_SERVICE_NAME = 'MSG_VR_DATA'

const.MSG_VR_AUDIO_INIT_SERVICE_TYPE = '0x00050002'
const.MSG_VR_AUDIO_INIT_SERVICE_NAME = 'MSG_VR_AUDIO_INIT'

const.MSG_VR_AUDIO_DATA_SERVICE_TYPE = '0x00050003'
const.MSG_VR_AUDIO_DATA_SERVICE_NAME = 'MSG_VR_AUDIO_DATA'

const.MSG_VR_AUDIO_STOP_SERVICE_TYPE = '0x00050004'
const.MSG_VR_AUDIO_STOP_SERVICE_NAME = 'MSG_VR_AUDIO_STOP'

const.MSG_VR_MODULE_STATUS_SERVICE_TYPE = '0x00050005'
const.MSG_VR_MODULE_STATUS_SERVICE_NAME = 'MSG_VR_MODULE_STATUS'

const.MSG_VR_AUDIO_INTERRUPT_SERVICE_TYPE = '0x00050006'
const.MSG_VR_AUDIO_INTERRUPT_SERVICE_NAME = 'MSG_VR_AUDIO_INTERRUPT'

### Touch ###
const.MSG_TOUCH_ACTION_SERVICE_TYPE = '0x00068001'
const.MSG_TOUCH_ACTION_SERVICE_NAME = 'MSG_TOUCH_ACTION'

const.MSG_TOUCH_CAR_HARD_KEY_CODE_SERVICE_TYPE = '0x00068008'
const.MSG_TOUCH_CAR_HARD_KEY_CODE_SERVICE_NAME = 'MSG_TOUCH_CAR_HARD_KEY_CODE'







