#----------------------------------------------------------------------
# This file was generated by C:\Users\djgv4b\AppData\Local\Programs\Python\Python39\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

import_file = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAADEElEQVRYR8WXS2gTURSG/3Mn'
    b'3SjSJk2h4MZiEwtWRFfFje2iBRG0G7spCqJImyioVCr4aBALSkV8TUJ9gOiuCC6qgkWsUhcW'
    b'RBEUbFLxAT6wdSK0C6Ez98iEpmTSTDLTJHWWd865/3f/e+6ZO4TsZ2hIqZ7e1MtABOCXDBoD'
    b'5AsPz41NhRtnF8UXOUB2+f5bH1YZf5UwEQ4CWA1gloBRSeJ6snvtgyJ1F9JtAdIRNeqnWgn9'
    b'AhM602MEDJcKpCBAWrQ6llCZEcpcOQPHk6HA+WLccAxginhj8bPEdMICwdyVDAcHlwrhCsAU'
    b'8cUSI2C0WiAEdiS7AsNLgXAPcC3eCkEjVjF+ooWCFiinMK4BUi5EEzcB7MsUIea9v8PB206F'
    b'MwrabQpQdTXRLBSMWjKZx7VwsMntbEtyYN6FxwDaLLVAtCHZXf/ODUQRAPEBgHqyXDishYOX'
    b'lwWgOjrRzhD3s/rC3WQosGdZAHLWAeizFqqv+48AgBYKkC+W6GNGcy4QYvlcC6+LFHUK5hvS'
    b'ETAuZotIAy3ZY0LwRpDoA9gL4LuYMRqmextmzDhXRehTJ8+A+JQjiwn3DNbPCXhOEtCemWNC'
    b'/jkUeFYQwKdOLFi1YJlQ3jKzWf1b7EAY2E2AH4w+EKpyuVQQICWesm3R85MJPSRlYNF7okeQ'
    b'c/1MFccIbFm1awdMACax1W6VxDxhGDSgeHAn5QbLAyCxkoGdlhZNqAWjwRGAebQc7W9WEHlo'
    b'jnWuyFn1iqIRjBUAPwTIZ8bkrIHc59oxznsA622jCRFi0hh8xRbAfOFVE7+IUONY1nnguKGg'
    b'UzEwWQhAJbJeu5xr5I8kyU0syCzqbbbH0K9Otkjip6UStcxDiLDEFBHUvH2gnNugsKfdIP1H'
    b'IYCybQM8aGQD/azjkm0j8kbj2wlUsh8PyzYwnyYSXw2Dv9h3wsFXFV698lu5TgN0tEnC5ryt'
    b'2BdN3ACwvxzFKEmvg+5ZUwhgF4ChcgCAcVRKvMkL4B38WEmGNJuGv/QQNKb5X7ego8PI+znO'
    b'8zUsmsm8NaUn+QcmNEowRw9HMwAAAABJRU5ErkJggg==')

